"""Page copy for the generated style landing pages.

One entry per id in `FancyText.STYLE_PAGES`. This lives here rather than in
the engine because it is only ever read at build time: shipping thirty-two
intros and ninety-six FAQ answers inside fancytext-core.js would put ten
kilobytes of prose on every page of the site to serve one of them.

Fields:

    tagline         the line under the h1
    intro_heading   the h2 above the prose; every one is different, because a
                    heading templated across thirty-two near-identical pages
                    is the tell that they are near-identical pages
    title           <title>, before the " | fontloom" suffix
    description     meta description
    intro / second  two paragraphs, specific to this style
    faq             (question, answer) pairs, rendered as h3/p and as
                    FAQPage JSON-LD
    aka             the other phrases people search for this style

`tools/build_style_pages.py` fails rather than falling back if a style has no
entry here.
"""

COPY = {
    'bold': {
        "tagline": 'The one styled alphabet nearly every device already renders',
        "intro_heading": 'Why bold text pastes into fields that have no bold button',
        "title": 'Bold Text Generator: Copy and Paste Bold Letters',
        "description": 'Turn ordinary typing into bold Unicode letters you can copy and paste into a bio, a spreadsheet header or a chat name. Digits get a bold form too.',
        "intro": "Of the styled alphabets tucked into Unicode's Mathematical Alphanumeric Symbols block, the serif bold run starting at U+1D400 is the one you can rely on almost anywhere. It is not a font setting and it does not switch your text to a heavier weight: each letter is a separate character that was drawn bold from the start. Bold is also one of the few styles here with its own digits, at U+1D7CE, so a year keeps its weight instead of dropping back to plain figures.",
        "second": 'The obvious home for it is a plain-text field that offers no formatting at all: a spreadsheet header row, the first line of a bio, a pinned note. The catch is that these are not the letters anyone types into a search box, so a bold name is a name nobody can look up, and screen readers either mangle the run or pass over it. Keep it to headings and display names rather than body copy.',
        "faq": [
            ('Why do the numbers change as well?',
             'Bold is one of a handful of these alphabets that Unicode gave matching digits, at U+1D7CE. Most of the other styles stop at the fifty-two letters, so a price or a date falls back to ordinary figures in the middle of a styled line. With bold you can set a whole heading, numerals included, without that seam showing.'),
            ('Will Facebook accept this in my name field?',
             'No. Facebook and LinkedIn validate real-name fields against ordinary letters and reject these characters outright. They do go through in a bio, an about section or a post, but remember that they are separate characters from A to Z, so nobody reaches you by typing your name into a search field.'),
            ('Is bold text bad for accessibility?',
             'In a paragraph, yes. Screen readers treat mathematical alphanumerics inconsistently, spelling them out, renaming them or skipping them without a word. A bold display name costs a listener one line. A bold sentence costs them the sentence, so leave the plain version in your text and save the styling for a heading.'),
        ],
        "aka": ['bold text generator', 'fancy bold letters', 'bold font copy and paste'],
    },
    'italic': {
        "tagline": 'Slanted Unicode letters, with one famous gap in the alphabet',
        "intro_heading": 'The italic alphabet, and the letter Unicode never encoded',
        "title": 'Italic Text Generator: Copy and Paste Slanted Letters',
        "description": 'Convert what you type into italic Unicode characters, then copy and paste the slanted result into a bio, a caption or a chat message with no formatting.',
        "intro": 'There is a hole in this alphabet and it has a good reason. When Unicode encoded the mathematical italic letters at U+1D434 it left out lowercase h, because ℎ was already in the standard as the Planck constant and the rule is never to encode the same character twice. The h you paste from here is that borrowed one. Everything else is a purpose-made italic character rather than a slant applied to normal text by a font.',
        "second": 'Italic earns its place where you would normally reach for emphasis and cannot: a film title inside a chat message, a quoted line in a Discord post, one word in a forum reply that should read as an aside. Numbers are the thing to watch. No italic digit set exists, so a date or a price in the middle of the line reverts to upright figures and the join is visible.',
        "faq": [
            ('Why does the lowercase h look different from the rest?',
             'Because it is a different character with a different history. Unicode had already encoded ℎ at U+210E for the Planck constant before the mathematical italic run existed, and it does not duplicate characters, so no italic h was added at U+1D455. Fonts draw the two from separate designs, which is why the h can sit slightly off.'),
            ('Can I get italic numbers?',
             'Not in this style. Unicode never encoded an italic digit run, so numerals stay plain here no matter what you type. If a line is mostly figures and you want them styled, bold, sans-serif, monospace and double-struck all have their own digits and will keep a phone number or a price consistent.'),
            ('Is this the same as pressing Ctrl and I?',
             'No. A word processor keeps your letters and tells the renderer to slant them, so the slant vanishes if the formatting is stripped. Here the letters themselves are swapped for different characters. That is why it survives a paste into a field with no formatting at all, and also why search cannot match it.'),
        ],
        "aka": ['italic text generator', 'italic font copy and paste', 'slanted text generator'],
    },
    'bold-italic': {
        "tagline": 'Weight and slant together, as one complete 52-letter set',
        "intro_heading": 'One complete run, no borrowed letters',
        "title": 'Bold Italic Text Generator: Copy and Paste Styled Text',
        "description": 'Bold italic Unicode letters you can copy and paste into a listing title, a subject line or a bio. One complete set of characters, no formatting required.',
        "intro": 'Bold leans on weight, italic leans on slant, and the run at U+1D468 does both at once in a single set of characters. It is one of the tidier alphabets in the block: fifty-two letters, upper and lower case, all encoded together, with nothing borrowed from an older corner of Unicode. That matters in practice, because the borrowed letters in script and fraktur are the ones that sometimes render a shade off from their neighbours. Here every letter comes from the same run.',
        "second": 'It is loud, and that is the point. One word set in bold italic in an otherwise plain listing title, forum post or newsletter subject line reads as the emphasised word without any markup being available. What it cannot do is numbers. There is no bold italic digit set, so any figure you type stays upright and unweighted. If your line is mostly numerals, choose a style that has them.',
        "faq": [
            ('How is this different from turning on bold and italic in an editor?',
             'An editor leaves your letters alone and records two attributes about them, which a plain-text field will discard the moment you paste. This generator hands back different characters that were drawn bold and slanted when they were encoded, so the appearance travels with the text into fields that have no formatting.'),
            ('What happens to my punctuation and spaces?',
             'They pass through untouched. Only the twenty-six upper and twenty-six lower case Latin letters have counterparts in this run, so commas, brackets, spaces and accented letters stay exactly as typed. Numerals stay plain too, since no bold italic digits were ever encoded. Expect a mixed line rather than a uniformly styled one.'),
            ('Will the styling survive if someone quotes my message?',
             "Usually, because there is nothing to strip: quoting, forwarding and copying all move the characters themselves. What can change is how they look, since that depends on the font on the reader's device rather than on yours. Somebody with incomplete font coverage sees empty rectangles where you see letters."),
        ],
        "aka": ['bold italic text generator', 'bold italic font copy paste', 'fancy bold italic letters'],
    },
    'script': {
        "tagline": 'The flowing look people mean when they search for fancy text',
        "intro_heading": 'What makes cursive text cursive',
        "title": 'Cursive Text Generator: Copy and Paste Script Letters',
        "description": 'Write in cursive script characters and copy and paste them straight into a bio, a caption or a message. No app, no font install, just Unicode letters.',
        "intro": 'Most people arrive here wanting one line of a bio to look handwritten, and this is the alphabet that does it. Unicode calls it mathematical script and put it at U+1D49C, where it stands in for the flowing capitals mathematicians use for sets and transforms. Eleven of its letters are not in that run at all: ℬ ℰ ℱ ℋ ℐ ℒ ℳ ℛ ℯ ℊ and ℴ already existed in the older Letterlike Symbols block, and Unicode does not encode a character twice.',
        "second": 'Those eleven are why a script name sometimes looks uneven, since a font may draw them from a different design than the rest of the set. Bold script is the fix if that bothers you, being one unbroken run. Otherwise this suits a display name, a caption or a wedding message, and suits nothing that anyone has to find later, because a search for your plain name will not match these letters.',
        "faq": [
            ('Does it work on Instagram?',
             "Bios, captions and comments are ordinary text fields, so pasted script characters appear there the way they appear anywhere else, subject to the reader's device font. Two things do not carry over. A hashtag written in script is a different hashtag from the plain one, and name search will not match the styled spelling."),
            ('Why do some letters look heavier or narrower than the others?',
             'Eleven of them come from a separate Unicode block that was designed years earlier. A font can draw those eleven with different proportions, a different stroke weight or a different slope than the main run, and the mismatch shows most in capitals. Bold script has no borrowed letters and stays even.'),
            ('Is cursive text the same as a handwriting font?',
             'No. A font is a file that redraws the letters you typed, and it only works where that file is installed. This swaps in characters that were designed to look cursive, so the appearance travels with the text into any field, at the cost of not being ordinary letters any more.'),
        ],
        "aka": ['cursive text generator', 'script font copy and paste', 'fancy cursive letters', 'handwriting text generator'],
    },
    'bold-script': {
        "tagline": 'The script alphabet without any of the borrowed letters',
        "intro_heading": 'The script alphabet without the seams',
        "title": 'Bold Cursive Text Generator: Copy and Paste Script Text',
        "description": 'Heavier cursive characters you can copy and paste into a bio, a header or a nickname. One clean Unicode run, so the letters render more evenly.',
        "intro": 'Thicker strokes, more contrast, and a set that holds together as one hand rather than two. Unicode placed bold script at U+1D4D0 as fifty-two consecutive characters, and unlike plain script none of them had to be borrowed from an older block to avoid a duplicate. Everything was drawn for the same run at the same time, which is the reason it tends to render more consistently across devices than the regular script alphabet does.',
        "second": 'That consistency makes it the better pick for anything short and prominent: a channel description header, a birthday post, the top line of a link-in-bio page. Nothing about your font changes when you use it, since you are swapping in different characters, so there is nothing for a plain-text field to strip. There are no bold script digits, though, so a date typed alongside stays in ordinary figures.',
        "faq": [
            ('Why does bold script render more reliably than plain script?',
             'Plain script has eleven letters pulled from the Letterlike Symbols block, which a font may draw from an unrelated design. Bold script is one uninterrupted run of fifty-two characters, so a font that covers the run at all covers it uniformly. You get one weight and one slope across the whole alphabet.'),
            ('Can I use it in a Discord nickname?',
             'Nicknames and server display names are plain text fields, so these characters go in the way any other text does. Two caveats worth knowing: nobody can find you by typing your real name, since these are not those letters, and plenty of servers have a rule requiring a readable, mentionable name.'),
            ('Does each letter count as one character or two?',
             'It depends who is counting. Every letter here is a single Unicode code point, but it needs two UTF-16 units to store, so a limit implemented the older way charges you double. That is why a bio fits fewer styled characters than plain ones on some sites and exactly the same number on others.'),
        ],
        "aka": ['bold cursive text generator', 'bold script font copy paste', 'fancy bold cursive letters'],
    },
    'fraktur': {
        "tagline": 'Blackletter, the printing hand behind the gothic font search',
        "intro_heading": 'Blackletter, and why everyone calls it gothic',
        "title": 'Gothic Font Generator: Copy and Paste Fraktur Letters',
        "description": 'Gothic blackletter characters ready to copy and paste into a name, a server label or a bio. Fraktur letterforms encoded as Unicode, not a font download.',
        "intro": 'Fraktur is a real printing hand, cut in Germany in the sixteenth century and used for German books well into the twentieth. Unicode carries it at U+1D504 because mathematicians kept reaching for blackletter capitals to name particular objects, not because anybody wanted a decorative alphabet. Five letters sit outside that run: ℭ ℌ ℑ ℜ and ℨ were already in Letterlike Symbols. Search traffic calls the result gothic, and this alphabet is what that search is after.',
        "second": 'It carries a lot of atmosphere per character, which is why it turns up in band names, Discord channel labels and tabletop character sheets. Blackletter is also genuinely harder to read than a roman face: at small sizes the capitals collapse into a picket fence of vertical strokes and long words slow a reader right down. Keep the run short. Digits have no fraktur form, so numbers stay ordinary.',
        "faq": [
            ('Is gothic the same as Old English lettering?',
             'They are cousins. Font catalogues label the dense, angular medieval hand Old English or textura, while fraktur is the slightly later German variety with broken curves and flourished capitals. Unicode encoded fraktur specifically. If you searched for gothic or Old English, this is the closest thing the standard actually contains.'),
            ('Why are C, H, I, R and Z drawn differently?',
             'Those five had already been encoded in the Letterlike Symbols block for mathematical use before the fraktur run existed, and Unicode does not encode a character twice, so the run skips them and reuses the older ones. A font drawing them from a separate design gives you five capitals that sit slightly apart.'),
            ('Can I use this for a tattoo or a logo mock-up?',
             'For a rough mock-up in a text field, yes. For finished artwork, no. What you copy is a string of characters, and how they look depends entirely on which font renders them, so the shapes change from device to device. Real design work wants an actual blackletter typeface with a licence.'),
        ],
        "aka": ['gothic font generator', 'fraktur text generator', 'blackletter text copy paste', 'old english text generator'],
    },
    'bold-fraktur': {
        "tagline": 'Blackletter with enough weight to survive at small sizes',
        "intro_heading": 'The heavier blackletter, and when to reach for it',
        "title": 'Bold Gothic Text Generator: Copy and Paste Blackletter',
        "description": 'Heavier gothic blackletter characters to copy and paste into a gamer tag, a clan prefix or a display name. Thicker strokes that hold up when shown small.',
        "intro": 'Plain fraktur has fine hairlines, and hairlines are the first thing to disappear when a name is rendered at fourteen pixels beside a profile picture. The bold run at U+1D56C thickens every stroke to fix exactly that. It is complete as well: all fifty-two letters sit consecutively, none of them borrowed, so you avoid the five odd capitals that give lighter fraktur its slightly mixed look. For blackletter that still reads at a glance, this is the version to take.',
        "second": 'Gamer tags, clan prefixes and short display names are where it earns its keep, since those get shown small and rarely need reading twice. Coverage is what to check before committing. The mathematical alphabets are a large block and a device missing them draws an empty rectangle for every letter, with no graceful fallback. Numbers have no blackletter form either, so a clan number typed in stays plain.',
        "faq": [
            ('When should I choose bold fraktur over plain fraktur?',
             'Whenever the text will be small or thin on screen. The bold run holds its shape in a member list, a leaderboard row or a fourteen-pixel display name, where plain fraktur loses its hairlines and turns into grey mush. Plain fraktur is the better choice for a longer line at a comfortable reading size.'),
            ('Do numbers get a blackletter form?',
             'No. Unicode encoded fraktur and bold fraktur as letters only, so digits are left as ordinary figures. A tag like a year or a squad number will sit in plain numerals next to your styled letters. Some people spell the number out to keep a line consistent, which is the only real workaround.'),
            ('Why do some devices show rectangles instead of letters?',
             'Because this is not a font you can install for your readers. You are sending characters, and a device whose fonts do not cover the mathematical block has nothing to draw with, so it falls back to the empty box that means no glyph available. Older phones and some smart TVs are the usual culprits.'),
        ],
        "aka": ['bold gothic text generator', 'bold blackletter text', 'bold fraktur copy paste'],
    },
    'double-struck': {
        "tagline": 'Blackboard bold, the way a lecturer writes the number sets',
        "intro_heading": 'Blackboard bold, off the blackboard',
        "title": 'Double-Struck Text Generator: Blackboard Bold Copy Paste',
        "description": 'Double-struck Unicode letters and digits to copy and paste into notes, chat or a heading. The outline style mathematicians use for the number sets.',
        "intro": 'The doubled stroke started as a workaround. A lecturer at a blackboard could not produce the bold of printed type, so the stem got drawn twice, and the convention stuck well enough that Unicode encoded it at U+1D538. Seven of the letters were already there: ℂ ℍ ℕ ℙ ℚ ℝ and ℤ, the number sets themselves, live in Letterlike Symbols and get reused. Digits exist too, at U+1D7D8, which is more than most alphabets here can claim.',
        "second": 'For a note about the reals or the integers in a chat window with no formula support, this is the shortest path from thought to message. Outside maths it reads as a hollow outline face and works for a short heading. The seven borrowed letters can look a shade heavier or narrower than their neighbours, and outline forms thin out badly at small sizes, so a whole paragraph of it is hard work.',
        "faq": [
            ('Why is it called blackboard bold?',
             'Printed maths books set the number sets in bold. Chalk cannot do bold, so lecturers copying those symbols onto a board doubled one stroke of each letter instead, and students copied the doubling back into their notes. The look outlived the problem, and Unicode eventually gave it its own characters.'),
            ('Which letters come from a different block, and does it matter?',
             'C, H, N, P, Q, R and Z were encoded earlier in Letterlike Symbols, so the run at U+1D538 skips them. It matters only visually: a font may draw those seven with a slightly different weight or width than the rest. In maths they are the letters you want most, and they are the best supported.'),
            ('Can I use this for maths in a chat with no LaTeX?',
             'For naming the sets, yes, and it beats writing R with a bar in front. It stops there. The shape is baked into each character rather than applied by a font, so you get letters and nothing else: no exponents, no fractions, no proper subscripts, and screen readers will make a mess of the line.'),
        ],
        "aka": ['double struck text generator', 'blackboard bold generator', 'outline text copy and paste'],
    },
    'monospace': {
        "tagline": 'Equal-width characters that hold a column in a plain text box',
        "intro_heading": 'Fixed-width letters in a field with no code block',
        "title": 'Monospace Text Generator: Copy and Paste Fixed-Width Text',
        "description": 'Fixed-width Unicode characters you can copy and paste to line up a small table or price list in a field that offers no code block and no formatting.',
        "intro": 'Say you want two columns in a field that has no table and no code block: a short price list in a forum post, a schedule in a chat. Every character in the monospace run at U+1D670 carries the same advance width, so ten of them occupy the same horizontal space on every line and the column edges stay where you put them. The digits at U+1D7F6 match, which is what makes numeric alignment possible rather than merely close.',
        "second": "The alignment holds only while a single font is drawing everything. If a reader's device is missing part of the block and substitutes another font for some characters, the widths stop matching and the column drifts. Spaces and punctuation are ordinary variable-width characters to begin with, so lean on the letters and digits to do the spacing. Where a real code block exists, use that instead.",
        "faq": [
            ('Will my columns line up for everyone?',
             'For most readers, yes, and for anyone whose device lacks part of the block, no. Fallback substitution brings in a font with different metrics and the alignment slips. Test with a short line first, keep the table narrow, and accept that this is a best effort rather than a guarantee.'),
            ('Is this the same as a code block?',
             'No, and where a code block is offered it is the better tool. A code block is formatting the app applies to normal letters. Here the fixed width belongs to the characters themselves, which is why it survives being pasted into a bio, a form field or a chat client that has no code formatting at all.'),
            ('Do the digits match the letters?',
             'Yes. Monospace is one of the minority of styles here with a matching digit run, at U+1D7F6, and the figures share the same advance width as the letters. That is essential for a price column, since a mix of styled letters and plain numerals would defeat the whole point of using this alphabet.'),
        ],
        "aka": ['monospace text generator', 'typewriter text copy paste', 'fixed width font generator'],
    },
    'sans-serif': {
        "tagline": 'The styled alphabet that barely looks styled at all',
        "intro_heading": 'The styled alphabet that barely looks styled',
        "title": 'Sans-Serif Text Generator: Copy and Paste Sans Letters',
        "description": 'Clean sans-serif Unicode characters to copy and paste anywhere. The subtlest style on the site, with matching digits for dates and phone numbers.',
        "intro": 'This is the quiet one. Of all the alphabets in the mathematical block, the sans-serif run at U+1D5A0 sits closest to the interface font your phone or browser is already using, so the difference between it and ordinary typing can come down to a small shift in letterfit. That is either the appeal or the problem, depending on what you came for. Digits are included at U+1D7E2, which keeps a date or a phone number consistent with the words around it.',
        "second": 'Weigh what you are giving up. These are not the letters A to Z, so the line stops being searchable, screen readers handle it unpredictably, and a real-name field will refuse it outright. Those are the same costs the loud styles carry, in exchange for a difference many readers will not consciously register. Worth it for a display name that should look deliberate rather than decorative; not worth much elsewhere.',
        "faq": [
            ('Why does it look almost identical to normal text?',
             'Because most interfaces already render you in a sans-serif face, and this alphabet was designed to be the sans-serif member of a family. On a device whose default is a serif, the difference is obvious. On a typical phone, it shows up mainly as slightly different spacing and letter shapes rather than a new look.'),
            ('Is there any point using it over plain letters?',
             'Sometimes. It marks a line as chosen rather than typed, which is enough for a display name or a heading in a plain-text field. If nobody would notice the difference in your particular context, plain letters are better, since they stay searchable and read correctly aloud.'),
            ('Which is more subtle, sans-serif or small caps?',
             'Sans-serif. Small caps changes the shape of every lowercase letter and is unmistakable at a glance, whereas this can be missed entirely. Small caps has a compensating advantage: its characters live in the main plane, so underlines and other combining marks sit on them cleanly, which is not true here.'),
        ],
        "aka": ['sans serif text generator', 'sans serif font copy paste', 'plain unicode text generator'],
    },
    'sans-bold': {
        "tagline": 'The heaviest of the sans alphabets, digits included',
        "intro_heading": 'The heaviest of the sans alphabets',
        "title": 'Sans-Serif Bold Text Generator: Copy and Paste Bold Sans',
        "description": 'The heaviest sans-serif characters in Unicode, with matching digits, ready to copy and paste into a heading, an announcement or a display name.',
        "intro": 'Put the two bolds beside each other and the difference is the serifs, not the weight. Serif bold has feet and modulated strokes; the sans-serif bold run at U+1D5D4 is a plain heavy letter with nothing on the ends, which makes it the blackest thing in the block once the size drops. Its digits sit at U+1D7EC, so a number inside a heading holds the same weight as the words on either side of it.',
        "second": 'A pinned announcement, a list header, a section label buried in a long description: anywhere a plain-text field gives you no headings of its own, one line of this supplies one. Restraint matters more here than with the lighter styles, since a full paragraph is tiring to read, and on a device that lacks the block every letter becomes an empty rectangle rather than degrading to something legible.',
        "faq": [
            ('How does this differ from the serif bold generator?',
             'Only in the letterforms. Both are complete bold alphabets with their own digits, encoded in the same block. Serif bold has bracketed feet and thick-to-thin strokes, which reads as traditional; sans-serif bold is uniform and blunt, which reads as an interface heading. Pick whichever matches the text it will sit next to.'),
            ('Can I mix it with normal typing in one line?',
             'Yes, and that is usually the right way to use it. Since these are just characters, you can paste three styled words at the front of a plain sentence and get a heading and body in a field that supports neither. Keep the searchable words in plain letters.'),
            ('Will text in this style show up in search?',
             'Not under its plain spelling. A search engine or a site search matches the characters it was given, and a bold sans A is not the letter A, so the word is effectively invisible to anyone typing normally. Anything that needs to be found should appear somewhere in ordinary letters as well.'),
        ],
        "aka": ['sans serif bold text generator', 'bold sans font copy paste', 'heavy bold text generator'],
    },
    'sans-italic': {
        "tagline": 'A slanted sans face for captions, credits and asides',
        "intro_heading": 'Slanted sans letters, and nothing else',
        "title": 'Sans-Serif Italic Text Generator: Copy and Paste Text',
        "description": 'Slanted sans-serif Unicode letters to copy and paste into a caption, a credit line or a bio. A complete 52-letter set with nothing borrowed.',
        "intro": 'If you are already using sans-serif bold for a header, this is the line that goes underneath it. The run at U+1D608 gives you all fifty-two letters slanted and without serifs, complete, with nothing borrowed from an older block to fill a gap. Set against the serif italic it reads cleaner and a little cooler, which suits a credit line, a photo caption or a short aside better than it suits a name. No italic digits exist, so numbers stay upright.',
        "second": 'The slant is the only signal here, and it is a quiet one. On a device without the mathematical block a fallback font may draw the characters with no slant at all, leaving you with what looks like plain text that mysteriously cannot be searched. Check it where it will actually be read, and keep a plain version of the words nearby whenever the meaning depends on them.',
        "faq": [
            ('Why do the letters sometimes appear upright?',
             "The slant belongs to the character, not to a style you applied, and a device missing these characters substitutes from another font. Depending on what it picks, you may see an upright approximation or an empty rectangle. Neither is something the page can control, since only the reader's installed fonts decide."),
            ('Why do dates and prices stay upright?',
             'Because there is no sans-serif italic digit run in Unicode. Only the letters were encoded, so every numeral you type falls through unchanged. In a caption that is usually fine. In a line built mostly from figures it looks like a mistake, and sans-serif or sans-serif bold, both of which have digits, will serve better.'),
            ('What pairs well with it?',
             'Sans-serif bold above it, for one: same skeleton, opposite weight, so a heading and caption look related rather than random. Serif styles fight with it. Keeping one styled line and letting everything else stay plain almost always looks more considered than styling several lines in different alphabets.'),
        ],
        "aka": ['sans serif italic text generator', 'slanted sans text', 'italic sans font copy paste'],
    },
    'sans-bold-italic': {
        "tagline": 'Four attributes stacked into one set of characters',
        "intro_heading": 'Heavy and slanted at the same time',
        "title": 'Sans-Serif Bold Italic Text Generator: Copy and Paste',
        "description": 'Heavy slanted sans characters you can copy and paste into a listing headline, a roster line or a bio. A complete Unicode alphabet, no font install.',
        "intro": 'The name is a stack of four decisions: no serifs, heavy, slanted, and a separate Unicode character for every one of the fifty-two letters. That combinatorial habit is why the mathematical block runs past a thousand characters, with serif and sans each encoded in regular, bold, italic and bold italic as independent alphabets. This one lives at U+1D63C and is complete, with nothing pulled in from an older block to patch a hole.',
        "second": 'Weight plus slant reads as urgency, which suits a short line at the top of a marketplace listing or an esports roster entry rather than a sentence. Two or three words is the useful range. There are no digits, so a price or a squad number beside it drops to plain figures and the mismatch is loud at this weight. None of it is searchable either, so the words that matter should appear plainly somewhere too.',
        "faq": [
            ('Is anything on the site heavier than this?',
             'Upright sans-serif bold looks heavier, because a slant scatters the strokes and costs you some apparent weight. Bold fraktur puts more ink on the screen than either but is far harder to read. Among the slanted alphabets, this is as heavy as Unicode goes.'),
            ('Why does Unicode have four separate italic alphabets?',
             'Because maths notation treats style as meaning. A bold italic vector and an upright italic scalar are different things on the page, so each combination needed its own character to survive being copied or converted. The side effect is a full grid of styled alphabets that anyone can borrow for a bio.'),
            ('Does it work in a YouTube title or channel name?',
             'They are text fields, so the characters go in. What follows is the trade. Search matches characters, so a styled word is not the plain word and will not be found by anyone typing it normally, which is a steep price on a title. A channel banner line or a description header costs you far less.'),
        ],
        "aka": ['sans serif bold italic text generator', 'bold italic sans text', 'heavy slanted text generator'],
    },
    'small-caps': {
        "tagline": 'Real small capital letters, not shrunken uppercase',
        "intro_heading": 'Real small capitals, and the two that do not exist',
        "title": 'Small Text Generator: Copy and Paste Small Caps Letters',
        "description": 'Small caps characters you can copy and paste into a bio, a byline or a link page. Built from real Unicode small capitals, with two known gaps.',
        "intro": 'Nothing here comes from the mathematical block. Small caps is assembled from characters that linguists needed: Latin letter small capital forms scattered across IPA Extensions, Phonetic Extensions and Latin Extended-D, each encoded to write a particular sound rather than to make a tidy alphabet. Two of them were never encoded at all. There is no small capital q and no small capital x anywhere in Unicode, so those two letters stay ordinary lowercase and you can see the join.',
        "second": 'Because these are ordinary letters from the main plane, combining marks sit on them properly, so an underline or a strikethrough behaves the way you would expect, which is not true of the mathematical alphabets. Type in capitals and they pass straight through untouched, being capital-shaped already. The overall effect is understated enough for section labels on a link page or a byline, where script or blackletter would be far too much.',
        "faq": [
            ('Why are q and x still lowercase?',
             'Because the characters do not exist. The small capital letters were added piecemeal for phonetic notation, and no phonetic alphabet ever needed a small capital q or x, so neither was encoded. Rather than leave a blank, this site keeps the plain lowercase letter, which is the least jarring of the available options.'),
            ('What happens if I type in capitals?',
             'They come out unchanged. A small capital is already the shape of a capital, only shorter, so there is nothing to convert an uppercase letter into. If you want the classic look, type the first letter of a word in capitals and the rest lowercase, and you get a full-height initial followed by small capitals.'),
            ('Can I add an underline or strikethrough to small caps?',
             'Yes, and this is the one style here where that works dependably. These characters live in the same plane as ordinary letters, so combining marks attach and render as intended. The mathematical alphabets frequently place those same marks badly, which is why crossed-out or underlined text is best built on this set.'),
        ],
        "aka": ['small caps generator', 'small text generator', 'tiny caps copy and paste'],
    },
    'circled': {
        "tagline": 'Bubble letters, older than most alphabets on this site',
        "intro_heading": 'Bubble letters, from the oldest block on the site',
        "title": 'Bubble Text Generator: Copy and Paste Circled Letters',
        "description": 'Circled bubble letters and numbers to copy and paste into a bio, a list or a caption. Long-established Unicode characters with wide font support.',
        "intro": 'Enclosed Alphanumerics is an old block, added well before the mathematical alphabets, and its age shows up as good font coverage: capitals from U+24B6, lowercase from U+24D0. The digits have a stranger history. Zero is a lone character of its own, ⓪ at U+24EA, while one through nine come from an earlier range of circled digits, so the ring around a zero is sometimes drawn a little differently from the ring around a nine.',
        "second": "They make usable bullets and step markers in a field with no list formatting, and they are the standard answer when somebody asks for bubble letters for a party invitation or a playful display name. The known gap is Android: some system fonts ship the capitals but not the lowercase set, and a missing character comes out as an empty rectangle. If you cannot predict your readers' devices, capitals are the safer half.",
        "faq": [
            ('Why does the zero look different from the other digits?',
             'Because it arrived separately. Unicode had circled one through nine from an earlier block and only later added a circled zero, ⓪ at U+24EA, in the Enclosed Alphanumerics range. A font that drew the two sets at different times can give the zero a slightly different ring size or weight than its neighbours.'),
            ('Which part of this set breaks most often?',
             'The lowercase letters. Some Android system fonts include the capitals from U+24B6 and stop there, so lowercase circled text turns into a row of empty rectangles on those devices. The digits are the most widely supported part of the block, and capitals are close behind them.'),
            ('Can I use circled letters as list bullets?',
             'That is one of the better uses for them. In a plain-text field with no list support, a circled letter or digit at the start of each line gives you numbered steps that survive copying, since the marker is part of the text. Keep to digits or capitals for the widest coverage.'),
        ],
        "aka": ['bubble text generator', 'circled letters copy and paste', 'bubble letters font'],
    },
    'negative-circled': {
        "tagline": 'White letters knocked out of solid black discs',
        "intro_heading": 'Filled circles, uppercase only',
        "title": 'Black Bubble Text Generator: Copy and Paste Filled Circles',
        "description": 'Filled black bubble characters to copy and paste into a tag, a badge or a short heading. Capitals and digits, with lowercase reusing the same glyphs.',
        "intro": 'Same idea as the circled alphabet with the colours swapped: the disc is filled and the letter is cut out of it, so a line of this reads as a row of badges rather than as writing. Each letter is its own character in the Enclosed Alphanumeric Supplement, starting at U+1F150, and there is a limitation built into the block. Only capitals were ever encoded. No lowercase negative circled set exists, so lowercase input comes back as the same filled capitals.',
        "second": 'The digits come from somewhere else entirely, the dingbat negative-circled numbers running from ⓿ through ❾, which is why they often render on devices where the letters do not. Letter coverage is thinner than for plain circled, these being much newer additions to the standard, and a device without them shows rectangles. Short and prominent is the use: a rank in a leaderboard post, a tag at the front of a line, three or four characters at most.',
        "faq": [
            ('Why does lowercase come out looking like uppercase?',
             'There is no lowercase version to give you. Unicode encoded a set of negative circled capitals and never added the matching lowercase, unlike the plain circled block which has both. Rather than drop your lowercase letters or leave them unstyled in the middle of a badge, this site maps them to the same filled capitals.'),
            ('Where do the filled digits come from?',
             'Not from the same block as the letters. They are dingbat characters, ⓿ and ❶ through ❾, which have been in Unicode far longer and appear in many more fonts. That mismatch in age is why a filled number often shows correctly on a device that draws empty rectangles for the filled letters beside it.'),
            ('Does it work on Instagram?',
             'Bios and comments take the characters like any other text, but this block is newer and less widely covered than plain bubble letters, so some readers will see rectangles where you see discs. Keep it to two or three characters, put nothing essential inside them, and use plain circled if you want safer coverage.'),
        ],
        "aka": ['black bubble text generator', 'filled circle letters', 'negative circled text copy paste'],
    },
    'squared': {
        "tagline": 'Boxed capital letters that paste into any plain text field',
        "intro_heading": 'Boxed capitals, with no lowercase anywhere',
        "title": 'Squared Text Generator: Boxed Letters to Copy and Paste',
        "description": 'Make squared text with boxed capital letters and copy and paste it anywhere plain text goes. Uppercase only, no squared digits, no font to install.',
        "intro": 'Each letter sits inside its own outlined box, which is why squared text reads like something stencilled onto a crate rather than written in a sentence. The characters come from the Enclosed Alphanumeric Supplement, a block Unicode added for exactly this kind of label. It is twenty-six uppercase tiles and nothing else, so whatever you type comes out capitalised, and any digit in your text stays an ordinary digit because squared numbers were never encoded.',
        "second": 'Nothing here is a font. Your text stays text; each letter is swapped for a different codepoint that happens to be drawn with a border, which is how the look survives a copy into a field that offers no styling at all. Good for a status tag at the front of a forum title or a channel name meant to read as a placard. Older Android system fonts miss part of this block and draw an empty rectangle instead.',
        "faq": [
            ('Why does my lowercase come out as capitals?',
             'Because there is no lowercase set to map to. The Enclosed Alphanumeric Supplement gives Unicode one squared alphabet and it is the uppercase one, so lowercase input is pointed at the same twenty-six tiles. If mixed case has to survive, small caps or one of the maths alphabets will keep the distinction that this style cannot.'),
            ('Can I square numbers as well as letters?',
             'No. Unicode has circled digits and parenthesized digits, but it never encoded a squared nought through nine, so numbers pass straight through unchanged. A model number comes out half boxed and half plain. If the digits matter visually, the bubble style covers the full range and gets you closer to an even line.'),
            ('What is the difference between this and the black squared style?',
             'Weight. This one draws an outline around the letter and leaves the middle open, so it stays legible at small sizes. The negative squared set inverts that: a solid tile with the letter knocked out of it, much darker in a run of ordinary text. Both live in the same neighbourhood of Unicode and share the uppercase-only limit.'),
        ],
        "aka": ['square text', 'boxed letters', 'square letter generator'],
    },
    'negative-squared': {
        "tagline": 'Solid tiles with the letter cut out, for lines that need weight',
        "intro_heading": 'Filled boxes, and the four letters that arrive in colour',
        "title": 'Black Squared Text Generator for Solid Tile Letters',
        "description": 'Generate black squared letters as solid filled tiles, then copy and paste them into a name, header or post. Uppercase only, and the set has no digits.',
        "intro": 'When a line has to stop someone scrolling, the negative squared set does more work than any amount of bold. Each character is a filled tile with the letter cut out of it, so a short word lands as a row of dark blocks. The set begins at U+1F170 alongside the outlined squares and inherits their limits exactly: twenty-six uppercase forms, no lowercase, and no digits, so numbers keep their ordinary shape in the middle of it.',
        "second": 'These are characters, not styling. Nothing about the text has changed except which codepoints it is built from, which is why the look travels through a copy into a username field that has never heard of formatting. The catch is density. On a pale background a run of solid tiles can read as a redaction bar rather than a word, and system fonts predating this block will show hollow rectangles where the letters should be.',
        "faq": [
            ('Is this the same as highlighting text?',
             'No. A highlight is formatting the app paints behind your words, and it disappears the moment the text moves somewhere else. These are letters drawn as filled tiles from the start, so the dark blocks are part of the string itself and arrive intact through any copy, paste or export.'),
            ('How many characters does one letter cost?',
             'One. Each capital maps to a single replacement, so what you type and what you get are the same length. That is not true of the underline and strikethrough styles, which hide a second character behind every letter. Symbol-heavy strings can still trip a length rule or a spam filter on a strict service.'),
            ('What happens to punctuation and spaces?',
             'They pass through untouched. The block covers the twenty-six capitals and nothing more, so full stops, hyphens, spaces and digits stay exactly as typed. In practice that reads better than a full conversion would, because the plain punctuation gives the eye somewhere to rest instead of one unbroken dark band.'),
        ],
        "aka": ['black square letters', 'inverted square text', 'filled box letters'],
    },
    'parenthesized': {
        "tagline": 'Bracketed letters and numbers, the way a list marker looks',
        "intro_heading": 'Bracketed letters, and the missing zero',
        "title": 'Parenthesized Text Generator: Letters in Brackets',
        "description": 'Put your text in parenthesized letters and numbers, then copy and paste the result. Full upper and lower case, digits 1 to 9, and no bracketed zero.',
        "intro": 'Unicode contains a full bracketed alphabet because a list marker sometimes has to be a character rather than something the layout draws for you. The lowercase forms sit at U+249C in Enclosed Alphanumerics, next door to the circled letters; the capitals were added later in a separate range at U+1F110; and the bracketed digits run from one to nine. There is no parenthesized zero anywhere in the standard, so a nought stays plain.',
        "second": 'Nothing is being formatted here. Each bracketed letter is a character in its own right, drawn with the parentheses already attached, which is why it holds up in a field that offers no styling. That makes it useful for a numbered set of options inside a chat message, a poll in an app that gives you no list formatting, or the steps of a plain-text recipe. Older system fonts may not carry the capital range and will show a box instead.',
        "faq": [
            ('Why does the zero stay plain?',
             'Because Unicode has no parenthesized zero. The bracketed digits start at one, which fits their purpose as list markers, since lists rarely begin at nought. Anything containing a zero therefore comes out mixed: in 2026 the two and the six get their brackets and the zero sits between them looking untouched.'),
            ('Does this style have real lowercase letters?',
             'Yes, and that makes it unusual here. The forms at U+249C are a genuine lowercase set, while the capitals live in a range added much later. Most enclosed styles, including both squared alphabets, only ever got capitals, so this is one of the few places where a mixed-case sentence keeps its shape.'),
            ('How do I number past nine?',
             'You build it digit by digit, and it shows. Ten arrives as a bracketed one followed by a plain zero rather than one character meaning ten. Unicode does contain bracketed numbers above nine as whole units, but this generator works through your text one character at a time, so it cannot combine them.'),
        ],
        "aka": ['bracket letters', 'letters in parentheses', 'parenthesis text'],
    },
    'regional-indicator': {
        "tagline": 'The letters country flags are built from, spaced so none form',
        "intro_heading": 'The letters that turn into flags',
        "title": 'Flag Letters Generator: Regional Indicator Text',
        "description": 'Write with regional indicator flag letters, spaced so no country flag forms, then copy and paste them into a nickname or header. One case, no digits.',
        "intro": 'Type GB with these letters and you do not get two tiles, you get a British flag, because building flags is what the regional indicator block is for. Country flag emoji are assembled from pairs of them. This generator puts a space between every letter so the pairs never form, which is the only dependable way to use the range as an alphabet. It starts at U+1F1E6, has one form per letter, and covers no digits.',
        "second": 'The result is a row of wide lettered squares with a lot of air around them, which suits a Discord nickname or a one-line header far better than a sentence. Those inserted spaces have a cost: a six-letter word occupies eleven characters, and a tight field will trim or refuse it. Nothing has been restyled either. The letters are separate characters that were drawn to serve as flag halves and are being borrowed.',
        "faq": [
            ('Why is there a space between every letter?',
             'To stop flags forming. Two regional indicators sitting next to each other that spell a valid country code render as that country flag, so the word GRAB would open with a Greek flag and carry on in letters. The inserted space breaks every pair, at the cost of making the text noticeably longer than what you typed.'),
            ('Can I still make an actual flag with these?',
             'Yes. Delete the space between the two letters of a country code so the pair sits adjacent. That is all a flag emoji is, two of these tiles side by side, which is also why a system without the flag artwork simply shows you the two lettered squares instead of the picture.'),
            ('Do capitals and lowercase come out differently?',
             'No, there is one tile per letter and both cases point at it. That is a limit rather than a fault: the block exists to encode country codes, which are always written in capitals, so a lowercase set was never needed. Digits have no equivalent here either and stay as ordinary numbers.'),
        ],
        "aka": ['flag letters', 'regional indicator symbols', 'emoji letter tiles'],
    },
    'faux-cyrillic': {
        "tagline": 'Cyrillic letters standing in for Latin ones, and not a word of Russian',
        "intro_heading": 'It looks Russian. It is not Russian.',
        "title": 'Faux Cyrillic Text Generator: Russian Looking Letters',
        "description": 'Swap Latin letters for Cyrillic lookalikes to get faux Russian text you can copy and paste. Not real Russian, and letters with no match stay as typed.',
        "intro": 'Д is not an A, И is not an N, and Я is not an R. What this style does is pick Cyrillic letters that resemble Latin shapes and stand them in, a swap of characters rather than a change of font, and the same trick paperback covers and film posters have leaned on for decades. Д is a d sound, И is an i, Я is closer to ya. It reads as Russian only to people who do not read Russian.',
        "second": 'Letters with no believable stand-in are left as Latin, so the effect is patchy by design, and the set carries no digits at all. That patchiness is arguably the honest part, since the style has always been a costume rather than a translation. It works on cover art, a band name or a clan tag where the reference is the whole point, and it works badly anywhere a reader might take you to be writing in the language.',
        "faq": [
            ('Is this actual Russian?',
             'Not remotely. The letters are genuine Cyrillic, but they were chosen purely for resembling Latin shapes, so the result spells nothing in any language that uses the alphabet. Д is a d sound, И is an i, Я is closer to ya. A Russian reader sees a string of unrelated consonants and vowels.'),
            ('Why did some of my letters not change?',
             'Because no convincing lookalike exists for them. Cyrillic and Latin share ancestry in places and diverge completely in others, so several letters have nothing to stand in. Rather than blank them out or force a poor match that breaks the illusion, this generator leaves those letters exactly as you typed them.'),
            ('What is it actually good for?',
             'Cover art, band names, a poster pastiche, a joke about a cold war thriller. It carries one very specific visual reference and almost nothing else, which is fine when that reference is what you want. Bear in mind that mixing scripts can trip filters on services watching for lookalike impersonation.'),
        ],
        "aka": ['russian style text', 'fake russian font', 'cyrillic looking letters'],
    },
    'greek-style': {
        "tagline": 'The symbol alphabet display names were made of in 2006',
        "intro_heading": 'The symbol alphabet the messenger era left behind',
        "title": 'Greek Style Text Generator: The MSN Era Alphabet',
        "description": 'Generate the old MSN and MySpace symbol alphabet and copy and paste it into a name or bio. One case only, no digits, and only some of it is Greek.',
        "intro": 'Before there were generators there were MSN Messenger display names, and this is the alphabet they were built from: α в ¢ ∂ є ƒ н ι, a scavenged mix of Greek, Cyrillic and stray symbol characters picked for looking roughly like the letter each one replaces. Fewer than half are actually Greek. There is one case, so shouting in capitals produces the same glyphs as typing quietly, and the set contains no digits.',
        "second": 'None of it is a font. Every character is a separate codepoint a renderer already knows, which is why a name built this way survives a copy into a field that would strip real styling on sight. The look has aged into something specific rather than merely dated, and it still suits a throwback handle or a playlist title. The mixture is the risk: some services reject names combining alphabets, and the characters come from so many blocks that their weights do not always match.',
        "faq": [
            ('Is this the Greek alphabet?',
             'Only partly. Characters like α, є and η are Greek, в and я are Cyrillic, and ¢, ƒ and ℓ are currency and letterlike symbols with no connection to either. The set was assembled by eye rather than by script, which is also why it has no digits and only one case.'),
            ('Why does typing in capitals change nothing?',
             'There is a single alphabet in this set, so uppercase and lowercase input land on the same characters. If a name needs a visible capital at the front, one option is to leave the first letter plain and run the rest through, which keeps the shape without pretending a second case exists.'),
            ('Will this get a username rejected?',
             'It might. Services restricting names to a basic character set will refuse it outright, and moderation systems watching for unusual scripts sometimes treat a symbol-heavy string as suspect. It is text and it pastes fine; whether a given field accepts it is a rule that field sets, not something the characters control.'),
        ],
        "aka": ['msn text', 'myspace font', 'greek letters text', 'symbol alphabet'],
    },
    'currency': {
        "tagline": 'Currency signs and stroked letters, the classic gamer tag look',
        "intro_heading": 'Money signs standing in for letters',
        "title": 'Currency Text Generator: Crossed Letters for Tags',
        "description": 'Turn a name into currency and crossed letters for gamer tags, then copy and paste it. One case, no digits, and J, Q and V have no match so stay plain.',
        "intro": 'The look is stroked metal. Every letter either carries a bar through it or has been replaced outright by a currency sign, which is why this alphabet has been showing up on gamer tags since long before anyone had a name for it. ₳ ฿ ₵ Đ Ɇ ₣ ₲ Ⱨ stand in for A through H. J, Q and V have nothing convincing available and come through as you typed them, and there are no digits in the set.',
        "second": 'On a tag it does exactly what it is asked to: five or six letters, heavy vertical strokes, legible at the size a scoreboard gives you. Whole sentences are another matter, since the bars start to fight each other and reading slows to a crawl. It is a plain character swap and not styling of any kind, so the tag you copy is the tag that appears. What varies is whether a service allows characters outside basic Latin in a name.',
        "faq": [
            ('Why are J, Q and V still plain?',
             'Because nothing in the currency and stroked-letter range looks enough like them. There is no widely supported J with a bar, and the nearest candidates for Q and V read as different letters entirely. Substituting a poor match would make the tag harder to read, so those three come through untouched.'),
            ('Are these real money symbols?',
             'Some are. ₳ is the Argentine austral, ฿ the baht, ₵ the cedi, ₦ the naira, ₩ the won. Others such as Đ, Ɇ and Ⱨ are ordinary Latin letters with a stroke added, borrowed from alphabets that need them. Mixed together they read as one alphabet rather than a list of currencies.'),
            ('Can I use this in a game name?',
             'It pastes anywhere text goes, since the letters are characters and not a font or a skin. Whether a particular game or storefront accepts them is a rule it sets for itself, and plenty restrict names to basic Latin. If yours is refused, try converting two or three letters instead of the whole tag.'),
        ],
        "aka": ['crossed letters', 'money symbol text', 'gamer tag font', 'stroked letters'],
    },
    'fullwidth': {
        "tagline": 'Double width letters from the CJK block, the aesthetic staple',
        "intro_heading": 'Double-width letters, borrowed from the CJK block',
        "title": 'Wide Text Generator: Fullwidth Vaporwave Letters',
        "description": 'Make fullwidth vaporwave text out of double width letters and copy and paste it into a caption. Safe almost everywhere, though long names may be cut off.',
        "intro": 'Of everything on this site, fullwidth is the least likely to break. The characters come from the CJK Fullwidth Forms block, which any font able to set Chinese, Japanese or Korean already covers in full, so ｖａｐｏｒｗａｖｅ turns up where a maths alphabet would fall back to empty boxes. Capitals sit at U+FF21, lowercase at U+FF41, digits at U+FF10, with the ideographic space U+3000 to keep the gaps in proportion.',
        "second": 'The doubled width is the whole point and also the whole cost. A display name that only just fitted will be cut off halfway, because the field counts characters while the screen counts pixels. One thing worth knowing before you experiment: do not layer combining underline or strikethrough marks on top of these. Each mark is drawn to the width of the character beneath it, so on double-width bases the marks meet end to end and merge into a solid bar over the text.',
        "faq": [
            ('Why is my name getting cut off?',
             'Because every character occupies two columns instead of one. A twenty-character limit still allows twenty characters, but they take up the width of forty, so the field runs out of room on screen long before it runs out of count. Shorten the phrase, or convert only part of it.'),
            ('Can I underline or strike through fullwidth text?',
             'Better not to. A combining mark is drawn to match the width of the character it attaches to, so on double-width letters the individual marks meet end to end and merge into one solid bar across the line, hiding the text underneath it. Choose one effect or the other rather than stacking them.'),
            ('Do I need to install anything?',
             'No, and no font is involved at any point. These are separate Unicode characters from the CJK Fullwidth Forms block that happen to be drawn wide, so any device capable of displaying Chinese, Japanese or Korean already has them all. That makes this one of the least likely styles to arrive as empty boxes.'),
        ],
        "aka": ['vaporwave text', 'aesthetic font', 'wide text', 'full width letters'],
    },
    'superscript': {
        "tagline": 'Raised letters and digits for exponents, units and footnotes',
        "intro_heading": 'Raised characters, and the eight capitals Unicode skipped',
        "title": 'Superscript Generator: Raised Letters and Exponents',
        "description": 'Generate superscript letters and digits for exponents, units and footnotes, then copy and paste them. Digits are complete; eight capitals do not exist.',
        "intro": 'Unicode never set out to provide a superscript alphabet, so what exists is leftovers: ¹ ² ³ inherited from Latin-1 and a scattering of raised letters borrowed from phonetic notation. The gaps are real and permanent. Capitals C, F, Q, S, V, X, Y and Z have no superscript form at all, and lowercase q has none either, so this site leaves those letters at full height rather than dropping a blank into your sentence. Digits are the exception, complete from ⁰ to ⁹.',
        "second": 'Where it earns its keep is any field with no formatting to offer: a listing that needs 45 m², a message carrying x², a footnote mark after a claim in a bio. None of this is styling applied to a letter. Each raised character is its own codepoint that happens to be drawn small and high, which is how it survives the trip into a spreadsheet cell. It is also finer than real superscript type, worth checking before you set anything small in it.',
        "faq": [
            ('Which letters are missing?',
             'Capitals C, F, Q, S, V, X, Y and Z have no superscript form anywhere in Unicode, and lowercase q has none either. Those characters stay at full size rather than becoming a blank, so a word containing them comes out uneven. Digits are the reliable part, with nought to nine all present.'),
            ('How do I type an exponent like x squared?',
             'Run the number through and place it after the base, so x followed by a raised two gives you x². The same approach handles units: a square metre becomes m² and a cubic one m³. It is notation for people to read, not something a calculator or a spreadsheet formula will evaluate.'),
            ('Why does it look smaller than superscript in a word processor?',
             'Because a word processor shrinks and raises the real letter, scaling whatever font you chose. Here the small shape is baked into the character by whoever drew the typeface, at whatever size they settled on. The result is usually finer and a little lighter, which matters in small print.'),
        ],
        "aka": ['small text above', 'exponent generator', 'raised letters', 'tiny text'],
    },
    'subscript': {
        "tagline": 'Lowered characters for formulae, indices and lab notes',
        "intro_heading": 'The thinnest set in Unicode',
        "title": 'Subscript Generator: Lowered Letters and Formulae',
        "description": 'Write subscript digits and letters for formulae like H₂O, then copy and paste them into any plain field. No capitals exist and most letters are missing.',
        "intro": 'H₂O and CO₂ are the reason this set exists. Unicode carries subscript characters so a formula can survive in a plain-text field, not so an entire sentence can be lowered, and the coverage reflects that narrow purpose. There are no subscript capitals whatsoever, and only about seventeen lowercase letters have one: a e h i j k l m n o p r s t u v x. Everything else arrives exactly as typed. The digits ₀ to ₉ are all present.',
        "second": 'Set against the superscript range, which at least has most of an alphabet, this is the thinnest style on the site, and a word run through it usually returns half lowered and half not. That is fine for what it is good at: an index like xₙ, a variable in a forum post about physics, a lab note in a field with no equation editor. The lowered characters are separate letters rather than a formatting switch, so no editor can strip them later.',
        "faq": [
            ('Why can I not lower a capital letter?',
             'There are no subscript capitals in Unicode, none at all. The set was added for scientific notation, where indices and formulae are written with lowercase letters and digits, so capitals were never encoded. If you need something like a capital N as an index, the usual workaround is to use its lowercase form.'),
            ('How do I write a chemical formula?',
             'Type it normally and lower only the counts: H, then a subscript two, then O. Because the digits nought to nine are all present, any formula built on numbers works completely, which covers most of chemistry. Ionic charges are the awkward case, since those want raised characters from the superscript set instead.'),
            ('Can I mix lowered and normal text in one line?',
             'That is the normal case here and the generator assumes it. Anything with no subscript character available passes through at full size rather than being dropped, so a sentence comes back part lowered and part plain. For a variable with an index, run only the index through and leave the letter alone.'),
        ],
        "aka": ['chemistry formula text', 'small text below', 'lowered numbers', 'index text'],
    },
    'strikethrough': {
        "tagline": 'The only way to cross something out where there is no format button',
        "intro_heading": 'A line through the text, drawn by the characters themselves',
        "title": 'Strikethrough Text Generator: Cross Out Any Text',
        "description": 'Cross out text with a real strikethrough you can copy and paste into any field. It uses combining marks, so every letter quietly costs two characters.',
        "intro": 'A price with a line through it says more than the word sale ever does, and in a field with no formatting button there is exactly one way to draw that line: U+0336, the combining long stroke overlay, appended after every character. The stroke is drawn across whatever it lands on, so the effect goes wherever the text goes. Spaces are skipped here, which is why the line breaks between words rather than running one unbroken rule across the phrase.',
        "second": 'The arithmetic catches people out. Because each stroke is its own character sitting invisibly behind a letter, a ten-letter word costs twenty characters against a bio limit, and the counter offers no hint as to why. Nothing you can see accounts for the missing room. That aside, it is the most portable trick on the site: no styling is involved, only extra characters, so an edited message or a finished item on a list keeps its stroke through every copy.',
        "faq": [
            ('Why does my bio say I am over the limit?',
             'Because the stroke is a character. Every letter you can see is followed by an invisible one that the counter includes, so a forty-character line arrives as eighty. Nothing on screen explains the gap. If a field is tight, strike only the words that need it and leave the rest untouched.'),
            ('Can I cross out just one word in a sentence?',
             'Yes, and it usually reads better than striking the whole line. Convert only the word or figure you want crossed, paste it back where it belongs, and type the rest normally. That is how an old price sitting beside a new one works, and how a correction stays visible in an edited post.'),
            ('Why does the line stop at every space?',
             'This site skips spaces deliberately, so each word gets its own stroke and the gaps stay open. A continuous rule across a phrase means striking the spaces too, which some fonts handle awkwardly. Word by word also survives wrapping better, since a line break falls in a gap rather than mid-stroke.'),
        ],
        "aka": ['crossed out text', 'line through text', 'cross out generator'],
    },
    'underline': {
        "tagline": 'A line under every letter, in fields that offer no formatting',
        "intro_heading": 'Underlining where there is no formatting button',
        "title": 'Underline Text Generator for Plain Text Fields',
        "description": 'Underline text with combining marks and copy and paste it into fields that have no formatting. It doubles the character count, and some sites strip it.',
        "intro": 'Underlined text on a screen has meant a hyperlink for as long as there has been a web, which is worth weighing before you use it, because readers will try to tap it. If that is acceptable, U+0332, the combining low line, does the job in any field with no formatting of its own. One mark follows each character and the line sits beneath. It stays tidy on ordinary letters and on small caps, and comes out ragged on the maths alphabets.',
        "second": 'No font has been swapped and nothing was installed: an underlined letter here is really two characters, the letter and an invisible mark travelling behind it, so the length you typed is not the length the field counts. A few platforms also strip combining marks when they save, and the line simply vanishes with no warning. It suits a heading inside a plain-text note, a subject line, or the top row of a table you have had to build out of spaces.',
        "faq": [
            ('Should I use a single or a double underline?',
             'It depends what you want the reader to assume. A single line has meant a hyperlink for as long as there has been a web, and people will try to tap it. Two lines carry no such association and read as emphasis or as a total. If the text is not clickable, the double form causes less confusion.'),
            ('Why did the underline disappear after I saved?',
             'Some platforms strip combining marks before storing text, and the low line is a combining mark. When that happens the letters survive and the underline does not, with no error to explain it. There is no fix from this side, and the same string usually keeps its line elsewhere, so test the field once.'),
            ('Why does it look ragged under bold or cursive letters?',
             'Because those styles come from the mathematical alphabets, whose letters are drawn at widths the low line was never fitted to. Each mark is sized to its own character, so the segments do not always meet and the line looks broken. On ordinary letters and on small caps it sits flat and joins up.'),
        ],
        "aka": ['underlined text', 'line under text', 'underscore text'],
    },
    'double-underline': {
        "tagline": 'Two rules underneath, the way a total gets marked',
        "intro_heading": 'Two rules instead of one',
        "title": 'Double Underline Text Generator: Two Line Emphasis',
        "description": 'Add a double underline to any text with combining marks, then copy and paste it. Two rules read as emphasis where a single line reads like a hyperlink.',
        "intro": 'An accountant draws a double rule under a total, and that convention is the entire argument for this style: two lines read as a conclusion where one line reads as something clickable. U+0333, the combining double low line, follows each character and draws both rules at once. It is a single mark rather than two stacked underlines, so you are not layering marks and hoping the spacing between them comes out even.',
        "second": 'The same arithmetic applies as everywhere in the combining family. One invisible character rides behind each visible one, so a fifteen-character heading arrives as thirty against whatever limit is doing the counting. No font has changed and nothing has been installed; you are shipping extra characters that a renderer knows to draw beneath the letter in front of them. Good for the last line of a plain-text invoice, or the one item on a checklist that is not optional.',
        "faq": [
            ('How is this different from underlining twice?',
             'You cannot underline twice in any useful sense, because stacking two low lines puts them in the same place. U+0333 is a single combining character that draws both rules at the correct spacing, which is why it looks deliberate rather than like a rendering accident. One mark per letter, exactly as with the single version.'),
            ('What is a double underline normally used for?',
             'Bookkeeping, mostly. A double rule under a figure marks it as final, the sum everything above adds up to, and the convention is old enough that people read it without being told. Away from accounts it works as strong emphasis in a plain-text note, or to mark the line in a list that is not negotiable.'),
            ('Will it survive being pasted into a document?',
             'Yes, because the marks are characters travelling with the text rather than formatting the app owns. What a word processor will not do is recognise them as its own underline feature, so the formatting menu shows the text as unstyled, and a spell checker may not recognise the word underneath.'),
        ],
        "aka": ['two lines under text', 'double underlined text', 'double line text'],
    },
    'slashed': {
        "tagline": 'A diagonal stroke per character, harder to miss than a strikethrough',
        "intro_heading": 'A diagonal stroke on every character',
        "title": 'Slashed Text Generator: Diagonal Line Through Text',
        "description": 'Put a diagonal slash through every letter and copy and paste the result. Heavier than a strikethrough, though some fonts draw the stroke very tall.',
        "intro": 'U+0338 puts a diagonal through every character rather than a horizontal, and the difference is more than decorative. The stroke cuts across the letterform at an angle nothing else in the alphabet uses, so the eye cannot skim past it. Where a strikethrough at small sizes can be mistaken for part of the type, a slash registers as deliberate cancellation the moment you look at it, which is the whole reason to reach for this one.',
        "second": 'Some fonts draw the combining solidus noticeably taller than the letter beneath it, so a slashed line can crowd the line above and look cramped in a narrow column. It carries the same doubled character count as the rest of the combining marks, too. Worth it when something has to be visibly void: a cancelled date on an event listing, a rule that no longer applies, a name on a roster who is out. It is a second character per letter, not a font effect.',
        "faq": [
            ('How is this different from a strikethrough?',
             'Angle and weight. A strikethrough lays a horizontal rule at mid height, which at small sizes can be mistaken for part of the letter. The solidus cuts diagonally, crossing the letterform in a direction nothing else in the alphabet uses, so it registers as cancellation immediately even in a crowded line.'),
            ('Why does the stroke stick up above the letters?',
             'Type designers draw the combining solidus long enough to cross a tall character, and it keeps that length on a short one. On some faces the top of the slash therefore rises well above lowercase letters and nudges the line above. Most plain-text fields give you no line spacing control to compensate.'),
            ('Can I slash a whole paragraph?',
             'You can, and it will be close to unreadable, which may well be the point. Two things to weigh: every character doubles, so a long block eats a length limit quickly, and the diagonals stack into visual noise over several lines. One slashed phrase inside plain text carries far more meaning.'),
        ],
        "aka": ['diagonal line through text', 'slash through letters', 'crossed letters'],
    },
    'overline': {
        "tagline": 'The bar that means an average or a repeating decimal',
        "intro_heading": 'The vinculum, surviving as plain text',
        "title": 'Overline Text Generator: Bars, Means and Vinculums',
        "description": 'Add an overline bar for means, repeating decimals and logic negation, then copy and paste it into a chat box or a spreadsheet cell. Plain text only.',
        "intro": 'A third written as a decimal is 0.3̅, and the bar over the three is not decoration, it is the notation. U+0305, the combining overline, is how that bar exists as a character rather than as something a layout draws. Mathematicians call it a vinculum: x̅ for a mean, a bar over the repeating block of a decimal, an overline for negation in logic. Put it after the character you want it above and it draws on top instead of underneath.',
        "second": 'The reason anyone needs this is that most of the places maths gets discussed have no equation editor: a chat box, a spreadsheet cell, a support ticket, a homework reply. Typing the bar as a character is the only way for the meaning to survive the trip, and there is no font to apply. The arithmetic bites here as elsewhere, though. A bar over four digits costs eight characters, and a platform that strips combining marks will hand back a plain x.',
        "faq": [
            ('How do I write a repeating decimal?',
             'Overline the digits that repeat and leave the rest alone. A third is a nought, a point, then a three carrying the bar. For something like a seventh, where six digits repeat before coming round again, run all six through so the bar spans the whole block and stops where the repetition does.'),
            ('Is the overline the same as a macron?',
             'They are different characters doing different jobs. A macron marks a long vowel and belongs to a single letter, which is why precomposed forms like ā exist. The overline is a vinculum, meant to span whatever it covers, so it is the one you want for a mean, a repeat bar or a negation.'),
            ('Can I put a bar over a whole expression?',
             'Only by overlining each character in it, one mark apiece. Adjacent bars are drawn to sit alongside one another, so a run of them reads as a single line above the span. It is also why the character count doubles across the entire expression, which tells against you in a field with a tight limit.'),
        ],
        "aka": ['bar over text', 'line above text', 'vinculum generator', 'repeating decimal bar'],
    },
    'upside-down': {
        "tagline": 'Turned lookalikes, reversed, so it reads when you flip the screen',
        "intro_heading": 'Nothing here is actually rotated',
        "title": 'Upside Down Text Generator: Flip Any Sentence',
        "description": 'Flip text upside down and reverse it so it reads when the screen is turned over, ready to copy and paste. Capitals are lowercased, since few can flip.',
        "intro": 'Nothing here is rotated, and no font is involved. Unicode simply happens to contain characters that look like turned Latin letters: ɐ ǝ ɥ ʇ began life in phonetic notation, ¿ and ¡ are Spanish punctuation, ⅋ is a turned ampersand. The generator swaps each letter for its lookalike and then reverses the whole string, so the last character comes first and the sentence reads correctly once you turn the screen over.',
        "second": 'Capitals mostly have no turned form, so the input is lowercased before anything else happens, and digits get only a partial set of substitutes with the rest left upright. Two further things are worth knowing. Some apps apply their own bidirectional text rules and quietly put the characters back into stored order, undoing the effect. And a screen reader announces that stored order, which is unlistenable, so keep this away from anything that has to be read rather than looked at.',
        "faq": [
            ('Why did my capitals turn into lowercase?',
             'Because turned capitals barely exist. Unicode has a decent stock of inverted lowercase shapes, inherited largely from phonetic notation, and almost nothing for uppercase, so the text is lowercased before flipping rather than left half converted. A name that depends on its initial capital loses it along the way.'),
            ('Why does one app show it the right way up?',
             'Because the trick is a reversed string, not a rotation, and some apps apply their own bidirectional text rules when deciding reading order. Where that happens the characters are put back the way they are stored, and the sentence reads forwards again in odd-looking letters. There is nothing to fix from this end.'),
            ('Is it a problem for accessibility?',
             'Yes, and it is worth taking seriously. A screen reader announces the characters in stored order, which is the sentence backwards, letter by letter, in phonetic symbols. It is unintelligible to listen to. Keep it to a joke reply or a caption, and never put anything someone needs to read in it.'),
        ],
        "aka": ['flip text', 'flipped text generator', 'reverse text upside down'],
    },
}
